[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.11.0"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.11"

[[constraint]]
  name = "github.com/gobuffalo/suite"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/going"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/grift"

[prune]
  go-tests = true
  unused-packages = true
